### ISSUE TITLE
JSON config properties should follow standard naming conventions

### ISSUE THREAD

**Issue by lincolnthree** [snowdrop/generator#13]
The JSON config properties are currently all first-letter capitalized. For properties that reflect industry terms/conventional configuration, however, these should follow the respective naming conventions. Other parameters simply don't need to be capitalized:

- [ ] Template -> template
- [ ] Bom -> bom
- [ ] Module -> module
- [ ] Name -> name
- [ ] Description -> description
- [ ] GroupId -> groupId
- [ ] ArtifactId -> artifactId
- [ ] Scope -> scope

`{"Template":["crud","rest","simple"],"Bom":[{"Community":"1.5.15.RELEASE","Snowdrop":"1.5.15.Final"},{"Community":"1.5.14.RELEASE","Snowdrop":"1.5.14.Final"},{"Community":"1.5.13.RELEASE","Snowdrop":"1.5.13.Final"}],"Module":[{"Name":"core","Description":"Core dependencies of a Spring Boot application","Starters":[{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter","Scope":""},{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-test","Scope":"test"}]},{"Name":"web","Description":"Web","Starters":[{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-web","Scope":""},{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-test","Scope":"test"}]},{"Name":"websocket","Description":"Websocket full-duplex communication and streaming of messages","Starters":[{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-websocket","Scope":""},{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-test","Scope":"test"}]},{"Name":"jaxrs","Description":"Apache CXF Starter implementing JAX-RS specification","Starters":[{"GroupId":"org.apache.cxf","ArtifactId":"cxf-spring-boot-starter-jaxrs","Scope":""},{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-test","Scope":"test"}]},{"Name":"hibernate","Description":"JPA \u0026 ORM with Hibernate","Starters":[{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-data-jpa","Scope":""},{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-jdbc","Scope":""},{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-test","Scope":"test"}]},{"Name":"monitoring","Description":"Monitor and manage your application using Jolokia, Prometheus, ...","Starters":[{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-actuator","Scope":""},{"GroupId":"org.springframework.boot","ArtifactId":"spring-boot-starter-test","Scope":"test"}]}]}`

**Comment by cmoulliard** [comment]
Should all the parameters be lower cases `groupId` -> `groupid` ? @lincolnthree

**Comment by lincolnthree** [comment]
I think keeping them the same as Maven conventions is important.

**Comment by cmoulliard** [comment]
Do you prefer that we display an array using the `singular` or `plural` word ?

```
  starters:
  - artifactid: spring-boot-starter-data-jpa
    groupid: org.springframework.boot
    scope: ""
  - artifactid: spring-boot-starter-jdbc
    groupid: org.springframework.boot
    scope: ""
...
```

OR

```
  starter:
  - artifactid: spring-boot-starter-data-jpa
    groupid: org.springframework.boot
    scope: ""
  - artifactid: spring-boot-starter-jdbc
    groupid: org.springframework.boot
    scope: ""
...
```
